name: Build and Publish Docker Image to GHCR

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: januschung
          password: ${{ secrets.GH_TOKEN }}

      - name: Set abbreviated sha
        run: |
          commit_sha=${{ github.sha }}
          echo "COMMIT_SHA=${commit_sha:0:7}" >> $GITHUB_ENV
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ghcr.io/januschung/job-winner-ui:${{ env.COMMIT_SHA }}
